[private]
default:
    @just --list

# Internal alias to execute the `atomic` command
[private]
atomic *args:
    #!/bin/bash
    just -f /etc/Justfile {{ args }}

# Bootstrap the current installation by installing brew & requested flatpaks.
[group('Bootstrap')]
bootstrap:
    @just install-taps

# Install brew
[group('Brew')]
[private]
install-brew:
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

[group('Brew')]
[private]
install-taps:
    /home/linuxbrew/.linuxbrew/bin/brew install gdb eza valgrind yazi zellij hyperfine luajit luarocks starship 

# Install brew packages `atomic brew ..`
[group('Brew')]
brew *pkgs:
    /home/linuxbrew/.linuxbrew/bin/brew install {{ pkgs }}

# Install flatpak packages
[group('Flatpak')]
flatpak *pkgs:
    #!/usr/bin/bash
    function flatpakif() {
        set -eoux pipefail
        if [[ -z "$(which flatpak)" ]]; then
            echo -e "flatpak is not installed";
        else
            flatpak $@
        fi
    }
    flatpakif install flathub --assumeyes --user {{ pkgs }}

[group('Bootc')]
target variant="base" version="42":
    sudo bootc switch --apply quay.io/ddimitrov/hyprland-atomic:{{ version }}-{{ variant }}
    sudo rpm-ostree rebase ostree-remote-registry:quay:quay.io/ddimitrov/hyprland-atomic:{{version}}-{{variant}}

[group('Bootstrap')]
copy-default-configs:
    #!/usr/bin/bash
    if [[ ! -f ~/.config/hypr/hyprland.conf ]]; then
        cp /usr/share/hypr/hyprland.conf ~/.config/hypr/hyprland.conf
    else
        echo "Hyprland configuration exists in home, skipping"
    fi
    if [[ ! -f ~/.config/ghostty/config ]]; then
        cp /usr/share/ghostty/config ~/.config/ghostty/config
    else
        echo "Ghostty configuration exists in home, skipping"
    fi

# Switch from the ISP-provided DNS servers to those provided by Cloudflare
[group('Bootstrap')]
use-cloudflare-dns:
    resolvectl dns {{ position }} 1.1.1.1 1.0.0.1
